code/unclogd/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :users, exept: :index
  resources :orders

  resources :items, only: [:index, :show] # /items

  get 'packages/:package_1_id,:package_2_id,:package_3_id', to: 'packages#show_multiple', as: :show_multiple_packages
  resources :packages


  get 'quiz', to: 'pages#quiz', as: :quiz
  resources :package_items

  get 'overview', to: 'users#overview', as: :overview


  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

code/unclogd/app/views/pages/home.html.erb
<link href="https://fonts.googleapis.com/css?family=Crimson+Text|Work+Sans" rel="stylesheet">
<div class="flash-screen">
  <div>
    <%= image_tag "logo_white.png", class: "flash-logo" %>
    <p>Find your perfect skincare</p>
    <button class="btn btn-info btn-lg" id="flash-button">Get started</button>
  </div>
</div>
<div class="main-container">
  <%= link_to items_path, class: 'browse-container' do %>
  <div class="col1">
  </div>
  <div class="col2">
    <%= image_tag 'magnifying-glass-white.svg', class: "picture" %>
    <h1>Browse</h1>
    <p>⟶</p>
  </div>
  <div class="col3">
    <div class="hidden-text">
      <p>Browse for skincare items<br>through carefully chosen products</p>
    </div>
  </div>
  <% end %>
  <%= link_to quiz_path, class: 'find-container' do %>
  <div class="col1">
  </div>
  <div class="col2">
    <%= image_tag 'solution.svg', class: "picture" %>
    <h1>Quiz</h1>
    <p>⟶</p>
  </div>
  <div class="col3">
    <div class="hidden-text">
      <p>Get matched with the perfect skincare products</p>
    </div>
  </div>
  <% end %>
  <div class="check-container">
    <div class="col1">
      <% if current_user.nil? %>
      <div class="homepage-login hidden-text">
        <ul>
          <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "main-navbar-link", id: "login" %>
          <%= link_to t(".sign_up", default: "Sign Up"), new_user_registration_path, class: "main-navbar-link", id: "signup" %>
        </ul>
      </div>
      <% end %>
    </div>
    <!--  </div> -->
    <div class="col2">
      <% if current_user %>
      <%= link_to user_path(current_user) do %>
      <%= image_tag 'tick-white.svg', class: "picture" %>
      <h1>Compare</h1>
      <p>⟶</p>
      <% end %>
      <% else %>
      <%= link_to new_user_session_path, id: "login" do %>
      <%= image_tag 'tick-white.svg', class: "picture" %>
      <h1>Compare</h1>
      <p>⟶</p>
      <% end %>
      <% end %>
    </div>
    <div class="col3">
      <div class="hidden-text">
        <p>Compare skincare products by ingredients</p>
      </div>
    </div>
  </div>
</div>
<!-- Modal Log-In Pop Up Form -->
<div class="bg-modal login">
  <div class="modal-content">
    <div class="close">+</div>
    <h4>Log In</h4>
    <div class="form">
      <%= simple_form_for(User.new, as: :user, url: session_path(:user)) do |f| %>
      <div class="form-inputs">
        <%= f.input :email,
                        required: false,
                        autofocus: true,
                        input_html: { autocomplete: "email" } %>
        <%= f.input :password,
                        required: false,
                        input_html: { autocomplete: "current-password" } %>
        <%= f.input :remember_me, as: :boolean  %>
        <div class="form-actions">
          <%= f.button :submit, "Submit", id: "button"%>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>
<!-- Modal Sign-up Pop Up Form -->
<div class="bg-modal signup">
  <div class="modal-content">
    <div class="close">+</div>
    <h4>Sign Up</h4>
    <div class="form">
      <%= simple_form_for(User.new, as: :user, url: registration_path(:user)) do |f| %>
      <%= f.error_notification %>
      <div class="form-inputs">
        <%= f.input :email,
                required: true,
                autofocus: true,
                input_html: { autocomplete: "email" }%>
        <%= f.input :password,
                required: true,
                hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                input_html: { autocomplete: "new-password" } %>
        <%= f.input :password_confirmation,
                required: true,
                input_html: { autocomplete: "new-password" } %>
      </div>
      <div class="form-actions">
        <%= f.button :submit, "Sign up" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

code/unclogd/app/views/pages/quiz.html.erb
<link href="https://fonts.googleapis.com/css?family=Crimson+Text|Work+Sans" rel="stylesheet">

<body>
  <div class="wrapper">
    <div class="column-left">
      <div class="img">
        <%= image_tag("image_example.png", size: "482x345") %>
      </div>
    </div>
    <div class="column-right">
      <%= simple_form_for @package do |f| -%>
      <div class="mm-survey">
        <div class="mm-survey-results">
          <div class="mm-survey-results-container">
            <h3 class="mm-survey-results-score"></h3>
            <ul class="mm-survey-results-list"></ul>
          </div>
          <div class="mm-survey-results-controller">
            <div class="mm-back-btn">
              <div class="btn">Back</div>
            </div>
          </div>
        </div>
        <div class="mm-survey-bottom">
          <div class="mm-survey-container">
            <div class="welcome">
              <h1>Welcome to your free skin consultation!</h1>
              <p> We are so excited to get to know you and your skin. The consultation will take about 5 minutes to complete and at the end, we will compile a personalized package for you. </p>
              </br>
              <div class="btn begin-btn" id='begin-survey'> Let's begin </div>
            </div>
            <div class="mm-survey-page" data-page="1">
              <div class="mm-survery-content">
                <div class="mm-survey-question">
                  <strong>
                    <p>What is your age range ?</p>
                  </strong>
                </div>
                <div class="mm-survey-item">
                  <input type="radio" id="radio01" data-item="1" name="package[quiz_results][age][]" value="<25" class="mm-next" />
                  <label for="radio01"><span></span>
                    <p>
                      < 25 </p> </label> </div> <div class="mm-survey-item">
                        <input type="radio" id="radio02" data-item="1" name="package[quiz_results][age][]" value="25-35" class="mm-next" />
                        <label for="radio02"><span></span>
                          <p> 25 - 35 </p>
                        </label>
                </div>
                <div class="mm-survey-item">
                  <input type="radio" id="radio03" data-item="1" name="package[quiz_results][age][]" value="36-45" class="mm-next" />
                  <label for="radio03"><span></span>
                    <p> 36 - 45 </p>
                  </label>
                </div>
                <div class="mm-survey-item">
                  <input type="radio" id="radio04" data-item="1" name="package[quiz_results][age][]" value="45+" class="mm-next" />
                  <label for="radio04"><span></span>
                    <p> 45 + </p>
                  </label>
                </div>
              </div>
            </div>
            <div class="mm-survey-page" data-page="2">
              <div class="mm-survery-content">
                <div class="mm-survey-question">
                  <p> You are: </p>
                </div>
                <div class="mm-survey-item">
                  <input type="radio" id="radio05" data-item="2" name="package[quiz_results][sex]" value="male" class="mm-next" />
                  <label for="radio05"><span></span>
                    <p> Male </p>
                  </label>
                </div>
                <div class="mm-survey-item">
                  <input type="radio" id="radio06" data-item="2" name="package[quiz_results][sex]" value="female" class="mm-next" />
                  <label for="radio06"><span></span>
                    <p> Female </p>
                  </label>
                </div>
              </div>
            </div>
            <div class="mm-survey-page" data-page="3">
              <div class="mm-survery-content">
                <div class="mm-survey-question">
                  <p>How would you describe your skin type?</p>
                </div>
                <div class="mm-survey-item">
                  <input type="radio" id="radio09" data-item="3" name="package[quiz_results][skin_type]" value="dry" class="mm-next" />
                  <label for="radio09"><span></span>
                    <p>Dry</p>
                  </label>
                </div>
                <div class="mm-survey-item">
                  <input type="radio" id="radio10" data-item="3" name="package[quiz_results][skin_type]" value="normal" class="mm-next" />
                  <label for="radio10"><span></span>
                    <p>Normal</p>
                  </label>
                </div>
                <div class="mm-survey-item">
                  <input type="radio" id="radio11" data-item="3" name="package[quiz_results][skin_type]" value="oily" class="mm-next" />
                  <label for="radio11"><span></span>
                    <p>Oily</p>
                  </label>
                </div>
                <div class="mm-survey-item">
                  <input type="radio" id="radio12" data-item="3" name="package[quiz_results][skin_type]" value="normal" class="mm-next" />
                  <label for="radio12"><span></span>
                    <p>Combination</p>
                  </label>
                </div>
                <div class="mm-survey-item">
                  <input type="radio" id="radio13" data-item="4" name="package[quiz_results][sensitivity]" value="normal" class="mm-next" />
                  <label for="radio13"><span></span>
                    <p> I am not too sure</p>
                  </label>
                </div>
              </div>
            </div>
            <div class="mm-survey-page" data-page="4">
              <div class="mm-survery-content">
                <div class="mm-survey-question">
                  <p>Do skincare products often irritate your skin?</p>
                </div>
                <div class="mm-survey-item">
                  <input type="radio" id="radio13" data-item="4" name="package[quiz_results][sensitivity]" value="sen0" class="mm-next" />
                  <label for="radio13"><span></span>
                    <p> Never </p>
                  </label>
                </div>
                <div class="mm-survey-item">
                  <input type="radio" id="radio14" data-item="4" name="package[quiz_results][sensitivity]" value="sen0" class="mm-next" />
                  <label for="radio14"><span></span>
                    <p> Rarely </p>
                  </label>
                </div>
                <div class="mm-survey-item">
                  <input type="radio" id="radio15" data-item="4" name="package[quiz_results][sensitivity]" value="sen1" class="mm-next" />
                  <label for="radio15"><span></span>
                    <p> Sometimes </p>
                  </label>
                </div>
                <div class="mm-survey-item">
                  <input type="radio" id="radio16" data-item="4" name="package[quiz_results][sensitivity]" value="sen1" class="mm-next" />
                  <label for="radio16"><span></span>
                    <p> Often </p>
                  </label>
                </div>
                <div class="mm-survey-item">
                  <input type="radio" id="radio17" data-item="4" name="package[quiz_results][sensitivity]" value="sen0" class="mm-next" />
                  <label for="radio17"><span></span>
                    <p> I do not know </p>
                  </label>
                </div>
              </div>
            </div>
            <div class="mm-survey-page" data-page="5">
              <div class="mm-survery-content">
                <div class="mm-survey-question">
                  <p> What is your primary skin concern? </p>
                </div>
                <div class="mm-survey-item">
                  <input type="radio" id="radio5a" data-item="5" name="package[quiz_results][concern]" value="aging" class="mm-next" />
                  <label for="radio5a"><span></span>
                    <p> Anti-Aging </p>
                  </label>
                </div>
                <div class="mm-survey-item">
                  <input type="radio" id="radio5b" data-item="5" name="package[quiz_results][concern]" value="acne" class="mm-next" />
                  <label for="radio5b"><span></span>
                    <p> Acne </p>
                  </label>
                </div>
                <div class="mm-survey-item">
                  <input type="radio" id="radio5c" data-item="5" name="package[quiz_results][concern]" value="uneven" class="mm-next" />
                  <label for="radio5c"><span></span>
                    <p>Uneven skin tone</p>
                  </label>
                </div>
                <div class="mm-survey-item">
                  <input type="radio" id="radio5e" data-item="5" name="package[quiz_results][concern]" value="pore" class="mm-next" />
                  <label for="radio5e"><span></span>
                    <p> Pore </p>
                  </label>
                </div>
                <div class="mm-survey-item">
                  <input type="radio" id="radio5f" data-item="5" name="package[quiz_results][concern]" value="acne" class="mm-next" />
                  <label for="radio5f"><span></span>
                    <p> I am not sure </p>
                  </label>
                </div>
              </div>
            </div>
            <div class="mm-survey-page" data-page="6">
              <div class="mm-survery-content">
                <div class="mm-survey-question">
                  <p> You prefer your skincare ingredients to be </p>
                </div>
                <div class="mm-survey-item">
                  <input type="radio" id="radio6a" data-item="6" name="package[quiz_results][q19]" value="Eco-friendly" />
                  <label for="radio6a"><span></span>
                    <p> Eco-friendly </p>
                  </label>
                </div>
                <div class="mm-survey-item">
                  <input type="radio" id="radio6b" data-item="6" name="package[quiz_results][q20]" value="Cruelty Free" />
                  <label for="radio6b"><span></span>
                    <p> Cruelty-Free </p>
                  </label>
                </div>
                <div class="mm-survey-item">
                  <input type="radio" id="radio6c" data-item="6" name="package[quiz_results][q21]" value="" />
                  <label for="radio6c"><span></span>
                    <p> Hypoallergenic </p>
                  </label>
                </div>
                <div class="mm-survey-item">
                  <input type="radio" id="radio6d" data-item="6" name="package[quiz_results][q21]" value="Hypoallergenic" />
                  <label for="radio6d"><span></span>
                    <p> No preference </p>
                  </label>
                </div>
              </div>
            </div>
            </br>
            </br>
            </br>
            <div class="mm-survey-controller">
              <div class="mm-prev-btn">
                <div class="btn">
                  < </div> </div> <div class="mm-finish-btn">
                    <%= f.button :button, "Submit" %>
                </div>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
    <div class="mm-survey-progress">
      <div class="mm-survey-progress-bar mm-progress"></div>
    </div>
</body>