code/unclogd/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :users, exept: :index
  resources :orders

  resources :items, only: [:index, :show] # /items

  get 'packages/:package_1_id,:package_2_id,:package_3_id', to: 'packages#show_multiple', as: :show_multiple_packages
  resources :packages


  get 'quiz', to: 'pages#quiz', as: :quiz
  resources :package_items

  get 'overview', to: 'users#overview', as: :overview


  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

code/unclogd/app/models/item.rb
class Item < ApplicationRecord
  has_many :package_items, dependent: :destroy
  has_many :packages, through: :package_items
  has_many :ingredient_lists
  has_many :ingredients, through: :ingredient_lists

  def price_in_cents
    case price
    when "Cheap"
      10_00
    when "Normal"
      20_00
    when "Expensive"
      35_00
    end
  end
end

code/unclogd/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item, only: [:show]

  def index
    if params[:query].present?
      sql_query = "name ILIKE :query OR brand ILIKE :query"
      @items = policy_scope(Item.where(sql_query, query: "%#{params[:query]}%"))
    else
      @items = policy_scope(Item.all)
    end
  end

  def show
    authorize @item
    @package_item = PackageItem.new(package: current_user.active_package, item: @item)
  end

  private

  def item_params
    params.require(:item).permit(:picture_url, :name, :ingredients, :cruelty, :price, :brand)
  end

  def find_item
    @item = Item.find(params[:id])
  end
end

code/unclogd/app/views/items/_item.html.erb
<link href="https://fonts.googleapis.com/css?family=Crimson+Text|Work+Sans|Karla" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<div class = "show-wrapper">
<div class="container">
	<div class="row padding-top">
		<div class="col-lg-4 col-lg-offset-2 col-xs-12">
			<div class="color-gray">
				<div class="picture-show">
					<%= image_tag(item.picture_url) %>
				</div>
			</div>
		</div>
		<div class="col-lg-6 col-xs-9">
			<p class="title"><strong><%= item.name %></strong></p>
			<p>Brand (Argentum)</p>
			<%= simple_form_for(@package_item) do |f| %>
			<%=  f.hidden_field :package_id %>
				<%=  f.hidden_field :item_id %>

			<p>Price (15 EUR)
				<%= f.button :button do %> <i class="fas fa-shopping-cart"></i>
			<% end %>
			<% end %></p>
			<ul class="nav nav-tabs-ingredients">
				<li class="active ingredient-text"><a class="link-tab" href="#tab-1">INGREDIENTS</a></li>
				<li class="ingredient-text last"><a class="link-tab" href="#tab-2">MORE INFORMATION</a></li>
			</ul>
			<div class="tab-content">
				<div id="tab-1" class="tab-pane active">
					<p> Water\Aqua\Eau; Bifida Ferment Lysate; Methyl Gluceth-20; Peg-75; Bis-Peg-18 Methyl Ether Dimethyl Silane; Butylene Glycol; Propanediol; Cola Acuminata (Kola) Seed Extract; Hydrolyzed Algin; Pantethine; Caffeine; Lecithin; Tripeptide-32; Ethylhexylglycerin; Sodium Rna; Bisabolol; Glycereth-26; Squalane; Sodium Hyaluronate; Oleth-3 Phosphate; Caprylyl Glycol; Lactobacillus Ferment; Oleth-3; Oleth-5; Anthemis Nobilis (Chamomile); Yeast Extract\Faex\Extrait De Levure; Choleth-24; Hydrogenated Lecithin; Ceteth-24; Tocopheryl Acetate; Ethylhexyl Methoxycinnamate; Hexylene Glycol; Carbomer; Triethanolamine; Trisodium Edta; Bht; Xanthan Gum; Phenoxyethanol; Red 4 (Ci 14700); Yellow 5 (Ci 19140) </p>
				</div>
				<div id="tab-2" class="tab-pane">
					<p>What we say Drum roll, standing ovation, sound the klaxon - this award-winning serum is a best-seller for a very good reason - it works! And boy does it work; containing exclusive technology it gets to work overnight on all signs of aging for brighter, more youthful skin come morning. Apply a few drops to your finger tips and really massage it into your skin for more hydration and fewer fine lines and wrinkles.</p>
				</div>
			</div>
		</div>
	</div>
</div>
</div>

code/unclogd/app/views/items/_item_card.html.erb
<div class="col-lg-3 col-md-4 col-sm-6 item-card">
  <%= link_to item_path(item) do %>
  <div class = "index-card">
    <div class = "picture-container">
      <div class = "item-picture">
        <%= image_tag(item.picture_url) %>
      </div>
    </div>
    <div class = "information">
      <% if current_page?(items_path) %>
        <h5><%= item.name.truncate(27) %></h5>
      <% else %>
        <h5><%= item.name %></h5>
      <% end %>
      <h5 class="padding-card"><strong><%= item.brand %></strong></h5>
      <% if defined? package_item %>
      <%= link_to package_item_path(package_item), method: :delete, data: {confirm: "are you sure?"} do  %>
        <i class="fas fa-trash"></i>
      <% end %>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

code/unclogd/app/views/items/index.html.erb
<div class="inner-container">
  <div class="row1 overfl">
    <div class="colA">
      <%= image_tag 'face1.png', class: "picture" %>
    </div>
    <div class="colB">
      <%= image_tag 'face2.png', class: "picture" %>
    </div>
    <div class="colC">
      <%= image_tag 'face3.png', class: "picture" %>
    </div>
    <div class="colD">
      <%= image_tag 'face4.png', class: "picture" %>
    </div>
  </div>
  <div class='search-bar col-md-offset-2 col-md-8'>
    <%= form_tag items_path, method: :get, class: "search-form" do %>
    <%= text_field_tag :query,
    params[:query],
    class: "flash flash-success",
    placeholder: "Find an item"%>
    <button type="submit" class="button1"><i class="fa fa-search"></i></button>
    <% end %>
  </div>
  <div class="container">
    <div class="row">
      <% @items.each do |item| %>
      <%= render 'item_card', { item: item } %>
      <% end %>
    </div>
  </div>
</div>

code/unclogd/app/views/items/show.html.erb
<%= render 'item', { item: @item } %>