code/unclogd/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :users, exept: :index
  resources :orders

  resources :items, only: [:index, :show] # /items

  get 'packages/:package_1_id,:package_2_id,:package_3_id', to: 'packages#show_multiple', as: :show_multiple_packages
  resources :packages


  get 'quiz', to: 'pages#quiz', as: :quiz
  resources :package_items

  get 'overview', to: 'users#overview', as: :overview


  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

code/unclogd/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
    <%= meta_title %>
    </title>
     <%= favicon_link_tag 'favicon.png'%>

    <meta name="description" content="<%= meta_description %>">
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META[" twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META[" twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body class="<%= controller_name %> <%= action_name %> <%= 'dashboard' if @dashboard %>">

    <%= link_to image_tag('logo_take2.png', class: "logo"), root_path, class: "logo" %>

    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= content_for?(:content) ? yield(:content) : yield %>

    <%  unless controller_name == 'pages' && action_name == 'home' %>
      <%= render 'shared/footer' %>
    <% end %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

code/unclogd/app/views/layouts/dashboard.html.erb
<link href="https://fonts.googleapis.com/css?family=Lato|Roboto" rel="stylesheet">

<% content_for :content do %>
<div class="container">
  <div class="container-grid">

    <nav class="side-nav">

      <ul class="dashboard-links" style="list-style-type:none;">
        <li class="<%= 'active' if @active_tab == "overview" %>"><%= link_to "MY ACCOUNT", overview_path %></li>
        <li class="<%= "active" if @active_tab == "account details" %>"><%= link_to "Account details", user_path(current_user) %></li>
        <li class="<%= "active" if @active_tab == "Orders" %>"><%= link_to "Orders", orders_path %></li>
        <li class="<%= "active" if @active_tab == "Root" %>"><%= link_to "Favourites", root_path %></li>
        <li class="<%= "active" if @active_tab == "Root" %>"><%= link_to "Address book", root_path %></li>
        <li class="<%= "active" if @active_tab == "Root" %>"><%= link_to "Payment details", root_path %></li>
        <li class="<%= "active" if @active_tab == "Root" %>"><%= link_to "Returns", root_path %></li>
        <li class="<%= "active" if @active_tab == "Root" %>"><%= link_to "<<<", root_path %></li>
      </ul>
    </nav>

    <main>
      <div class="container bootstrap center" style="overflow: auto; width:710px; height:600px;">

        <%= yield %>

      </div>

    </main>
  </div>
</div>


<% end %>
<% @dashboard = true %>

<%= render template: "layouts/application" %>