code/unclogd/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :users, exept: :index
  resources :orders

  resources :items, only: [:index, :show] # /items

  get 'packages/:package_1_id,:package_2_id,:package_3_id', to: 'packages#show_multiple', as: :show_multiple_packages
  resources :packages


  get 'quiz', to: 'pages#quiz', as: :quiz
  resources :package_items

  get 'overview', to: 'users#overview', as: :overview


  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

code/unclogd/app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

code/unclogd/app/views/shared/_footer.html.erb
<% if user_signed_in? %>
<div class="footer-wrapper">
  <div class="footer-bottom">
    <div class="footer-links">
      <a href="https://www.instagram.com" target="_blank"><i class="fab fa-instagram"></i></a>
      <a href="https://www.facebook.com" target="_blank"><i class="fab fa-facebook"></i></a>
      <a href="https://www.twitter.com" target="_blank"><i class="fab fa-twitter"></i></a>
      <a href="https://www.gmail.com" target="info@unclogd.com"><i class="far fa-envelope"></i></a>
    </div>
  </div>
</div>
<% end %>

code/unclogd/app/views/shared/_navbar.html.erb
<link href="https://fonts.googleapis.com/css?family=Crimson+Text|Work+Sans|Karla" rel="stylesheet">
<!-- <div class="navbar"> -->
  <!-- Right Navigation -->
  <div class="main-nav">
    <% if user_signed_in? %>
      <ul class="hidden-xs hidden-sm">
        <li><%= link_to "Search", items_path, class: "is-active search" %></li>
        <li><%= link_to "Quiz", quiz_path %></li>
        <li><%= link_to "Account", user_path(current_user) %></li>
        <li><%= link_to "Basket", package_path(current_user.active_package) %></li>
        <li><%= link_to "Compare", package_path(current_user.active_package) %></li>
        <li><%= link_to t(".sign_out", default: "Log out"), destroy_user_session_path, method: :delete %></li>
      </ul>

        <a href="#" class="main-nav-trigger hidden-xs hidden-sm">
          <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
        </a>
    <% end %>
    <!-- Login Link (when logged out) -->
    <!-- Dropdown list appearing on mobile only -->
    <div class="hidden-md hidden-lg">
      <% if user_signed_in? %>
      <div class="dropdown dropdown-content">
        <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-dropdown-menu">
          <li><%= link_to "Search", items_path, class: "is-active search" %></li>
          <li><%= link_to "Quiz", quiz_path %></li>
          <li><%= link_to "Account", user_path(current_user) %></li>
          <li><%= link_to "Basket", package_path(current_user.active_package) %></li>
          <li><%= link_to "Compare", package_path(current_user.active_package) %></li>
          <li><%= link_to t(".sign_out", default: "Log out"), destroy_user_session_path, method: :delete %></li>
        </ul>
      </div>
      <% end %>
    </div>
  </div>
<!-- </div> -->